In [1]:
import numpy as np

“输出列表特定行列”

In [2]:
np.random.seed(0)
x=np.random.randint(0,10,(5,5))
print(x)
print(x[1:3,:4])

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
[[9 3 5 2]
 [7 6 8 8]]



切片得到原数组的视图而非副本

In [3]:
x_sub = x[:,:]
x_sub[0,0] = 99
print(x)

[[99  0  3  3  7]
 [ 9  3  5  2  4]
 [ 7  6  8  8  1]
 [ 6  7  7  8  1]
 [ 5  9  8  9  4]]


创建副本用copy()实现

In [4]:
x_copy = x[:3,:3].copy()
print(x_copy)
x_copy[0,0] = 114
print(x_copy)
print(x)

[[99  0  3]
 [ 9  3  5]
 [ 7  6  8]]
[[114   0   3]
 [  9   3   5]
 [  7   6   8]]
[[99  0  3  3  7]
 [ 9  3  5  2  4]
 [ 7  6  8  8  1]
 [ 6  7  7  8  1]
 [ 5  9  8  9  4]]


In [5]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([5, 6, 7])
np.concatenate([x, y,z])

array([1, 2, 3, 3, 2, 1, 5, 6, 7])

数组的拼接

In [6]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.concatenate([grid, grid]))    #沿第一个轴拼接
print(np.concatenate([grid, grid], axis=1))   #沿第二个轴拼接

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


沿着固定维度处理数组时，使用 np.vstack（垂直栈）和 np.hstack（水平栈）函数会更简洁：

In [7]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
print(np.vstack([x, grid]))
y = np.array([[99],
              [99]])
print(np.hstack([grid, y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


拆分数组

In [8]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


相关的 np.hsplit和 np.vsplit的用法也类似：

In [9]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


python作为解释型语言，执行效率偏低

In [10]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
print(compute_reciprocals(values))

# big_array = np.random.randint(1, 100, size=1000000)
# %timeit compute_reciprocals(big_array)

[0.16666667 1.         0.25       0.25       0.125     ]


NumPy 为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，也被称作向量操作。
你可以通过简单地对数组执行操作来实现，这里对数组的操作将会被用于数组中的每一个元素。
比较以下两个结果

In [11]:
# print(compute_reciprocals(values))
# print(1.0 / values)
# %timeit (1.0 / big_array)

通用函数其他功能实例

In [12]:
#两数组数字对应相除
print(np.arange(5) / np.arange(1, 6))
#高维数组数取平方
x = np.arange(9).reshape((3, 3))
print(x**2)

[0.         0.5        0.66666667 0.75       0.8       ]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


通用函数运算

1.数值运算

In [13]:
x = np.arange(4)
print("x     =", x)   
print("x + 5 =", x + 5)    #np.add
print("x - 5 =", x - 5)    #np.substract
print("x * 2 =", x * 2)    #np.multiply
print("x / 2 =", x / 2)    #np.divide
print("x // 2 =", x // 2)  #np.flood_divide 
print("x ** 2 =", x ** 2)  #np.power

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]


2.绝对值 

In [14]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(np.abs(y))     # 对复数取模

[2 1 0 1 2]
[5. 5. 2. 1.]


3.三角函数/反三角函数

In [15]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


这些值是在机器精度内计算的，所以有些应该是 0 的值并没有精确到 0

In [16]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


4.指数和对数

In [17]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(2, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [2 4 8]


In [18]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [19]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


5.平方根

In [20]:
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,9,25])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 3. 5.]


其他函数

In [21]:
from scipy import special

In [22]:
# 误差函数（高斯积分）
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [23]:
# Gamma函数（广义阶乘，generalized factorials）和相关函数
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


高级通用函数

1.指定输出

In [24]:
#不同于创建临时数组，你可以用这个特性将计算结果直接写入到你期望的存储位置。
#所有的通用函数都可以通过 out参数来指定计算结果的存放位置不同于创建临时数组，你可以用这个特性将计算结果直接写入到你期望的存储位置。
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


2.聚合

In [25]:
#一个 reduce方法会对给定的元素和操作重复执行，直至得到单个的结果。
x = np.arange(1,6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

15
120


In [26]:
#accumulate可用于储存中间结果
print(np.add.accumulate(x))

[ 1  3  6 10 15]


3.外积

In [27]:
#任何通用函数都可以用 outer方法获得两个不同输入数组所有元素对的函数运算结果
print(np.multiply.outer(x, x))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


基本统计函数：求和，平均数，中位数，方差，标准差，Max,Min，分位数，

In [28]:
np.random.seed(0)
x = np.random.randint(1,100,8)
print(x)
print(np.sum(x))
print(np.mean(x))  #平均数
print(np.median(x))  #中位数
print(np.var(x))  #方差
print(np.std(x))    #标准差
print(np.max(x),np.argmax(x))   #查找最大值，最大值位置
print(np.min(x),np.argmin(x))
print(np.percentile(x,20))

[45 48 65 68 68 10 84 22]
410
51.25
56.5
553.6875
23.53056522908024
84 6
10 5
31.200000000000003
